### ISSUE TITLE
Add support for mobile mentions (discord is stoopid bro)

### ISSUE THREAD

**Issue by link1183** [link1183/rp-bot#12]

**Comment by jubnl** [comment]
? il se passe quoi avec discord ?

**Comment by link1183** [comment]
En gros pour le footer des perles (l'author de la perle) j'utilise une regex pour match une ou plusieurs mentions (je suis obligé de faire ça parce qu'il peut y avoir 1 ou plusieurs mentions dans le footer).

Ma regex elle match les string sous la forme <@123456789> (avec un id).

Ça ça fonctionne pour les mentions que tu fais sur le client pc. Si t'utilises le client android ou apple (enfin mobile quoi) les mentions vont être sous la forme <@!123456789> parce que nique toi et j'avais oublié ça
